# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e320c8472b111926c8e5231584cfcb0af0df21e1061239170b39f137241cc945886572f0ee6f78b3d1bae45e0e04e316f07b2f216c39ea1f5fe1ec4b820d863

test:
  secret_key_base: 8db5af8620b15d18e3e163d3ed2629c01adbeaa417650adf03f73a1c0d1ead8bbcabed9e531f306648aa303d42ff9a62a0b95972c33590b753f8dea7fd9d342d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
